#!/bin/bash -ex

dl() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    cd $2; curl -L -f -O $PROXY $1; cd -
}

VERSION="4.5.7"
URL="http://mirrors.owncloud.org/releases/owncloud-${VERSION}.tar.bz2"

dl $URL /usr/local/src

