#!/bin/bash -ex

dl() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    cd $2; curl -L -f $PROXY $1 > $3; cd -
}

VER="9.0.51"
URL="https://download.nextcloud.com/server/releases/nextcloud-${VER}.zip"

dl $URL /usr/local/src nextcloud-$VER.zip
