#!/bin/bash -ex

DB_NAME=owncloud
DB_USER=owncloud
DB_PASS=$(mcookie)

ADMIN_NAME=admin
ADMIN_PASS=turnkey

WEBROOT=/usr/share/owncloud


# tweak footer
TEMPLATE=$WEBROOT/core/templates/layout.guest.php
sed -i "s|<footer>.*|<footer><p class='info' style='width: auto \!important;'><a href='https://www.turnkeylinux.org/owncloud'>ownCloud Appliance</a> \&ndash; Powered by <a href='https://www.turnkeylinux.org'>TurnKey Linux</a></p></footer>|" $TEMPLATE

# tweak xcache
XCACHEINI=/etc/php5/apache2/conf.d/20-xcache.ini

sed -i "s|xcache.admin.enable_auth.*|xcache.admin.enable_auth = Off|" $XCACHEINI
sed -i "s|xcache.var_size.*|xcache.var_size = 32M|" $XCACHEINI

# configure apache
a2dissite 000-default
a2ensite owncloud.conf
a2enmod rewrite

# start services
service mysql start
service apache2 start

# setup the database
MYSQL_BATCH="mysql --user=root --password=$MYSQL_PASS --batch"
MYSQL_ADMIN="mysqladmin --user=root --password=$MYSQL_PASS"

$MYSQL_ADMIN create $DB_NAME
$MYSQL_BATCH --execute "grant all privileges on $DB_NAME.* to $DB_USER@localhost identified by '$DB_PASS'; flush privileges;"

# autoconfig curl based install
cat >$WEBROOT/config/autoconfig.php<<EOF
<?php
\$AUTOCONFIG = array(
     "adminlogin" => "$ADMIN_NAME",
     "adminpass" => "$ADMIN_PASS",
     "directory" => "$WEBROOT/data",
     "dbtype" => "mysql",
     "dbname" => "$DB_NAME",
     "dbuser" => "$DB_USER",
     "dbpass" => "$DB_PASS",
     "dbhost" => "localhost",
     "dbtableprefix" => "",
);
EOF

chown www-data:www-data $WEBROOT/config/autoconfig.php
curl -kc /tmp/cookie -b /tmp/cookie https://127.0.0.1/index.php
rm -f $WEBROOT/config/autoconfig.php
rm -f /tmp/cookie

# stop services
service mysql stop
service apache2 stop

