#!/bin/bash -ex

DB_NAME=owncloud
DB_USER=owncloud
DB_PASS=$(mcookie)

ADMIN_NAME=admin
ADMIN_PASS=turnkey

WEBROOT=/var/www/owncloud

# setup repo and pinning
_CODENAME="Debian_$(lsb_release -rs | cut -d "." -f 1).0"
REPO="http://download.opensuse.org/repositories/isv:/ownCloud:/community/$_CODENAME"
REPO_LABEL="Latest stable community release of ownCloud ($_CODENAME)"

cat >/etc/apt/sources.list.d/owncloud.list<<EOF
deb $REPO/ /
EOF

cat >/etc/apt/preferences.d/owncloud<<EOF
Package: *
Pin: release l=$REPO_LABEL
Pin-Priority: 100

Package: owncloud
Pin: release l=$REPO_LABEL
Pin-Priority: 500
EOF

curl $REPO/Release.key | apt-key add -

# install owncloud
apt-get update
DEBIAN_FRONTEND=noninteractive apt-get --force-yes --assume-yes install owncloud

# tweak footer
TEMPLATE=$WEBROOT/core/templates/layout.guest.php
sed -i "s|<footer>.*|<footer><p class='info' style='width: auto \!important;'><a href='http://www.turnkeylinux.org/owncloud'>ownCloud Appliance</a> \&ndash; Powered by <a href='http://www.turnkeylinux.org'>TurnKey Linux</a></p></footer>|" $TEMPLATE

# tweak xcache
XCACHEINI=/etc/php5/conf.d/20-xcache.ini
sed -i "s|xcache.admin.enable_auth.*|xcache.admin.enable_auth = Off|" $XCACHEINI
sed -i "s|xcache.var_size.*|xcache.var_size = 32M|" $XCACHEINI

# configure apache
a2dissite default
a2ensite owncloud
a2enmod rewrite

# start services
/etc/init.d/mysql start
/etc/init.d/apache2 start

# setup the database
MYSQL_BATCH="mysql --user=root --password=$MYSQL_PASS --batch"
MYSQL_ADMIN="mysqladmin --user=root --password=$MYSQL_PASS"

$MYSQL_ADMIN create $DB_NAME
$MYSQL_BATCH --execute "grant all privileges on $DB_NAME.* to $DB_USER@localhost identified by '$DB_PASS'; flush privileges;"

# autoconfig curl based install
cat >$WEBROOT/config/autoconfig.php<<EOF
<?php
\$AUTOCONFIG = array(
     "adminlogin" => "$ADMIN_NAME",
     "adminpass" => "$ADMIN_PASS",
     "directory" => "$WEBROOT/data",
     "dbtype" => "mysql",
     "dbname" => "$DB_NAME",
     "dbuser" => "$DB_USER",
     "dbpass" => "$DB_PASS",
     "dbhost" => "localhost",
     "dbtableprefix" => "",
);
EOF

chown www-data:www-data $WEBROOT/config/autoconfig.php
curl -c /tmp/cookie -b /tmp/cookie http://127.0.0.1/index.php
$MYSQL_BATCH --execute "USE $DB_NAME; show tables;"
rm -f $WEBROOT/config/autoconfig.php
rm -f /tmp/cookie

# stop services
/etc/init.d/mysql stop
/etc/init.d/apache2 stop

