#!/bin/sh -ex

DB_NAME=owncloud
DB_USER=owncloud
DB_PASS=$(mcookie)

ADMIN_NAME=admin
ADMIN_PASS=turnkey

SRC=/usr/local/src
WEBROOT=/var/www/owncloud

# unpack and tweak permissions
tar -xjf $SRC/owncloud-*.tar.bz2 -C $(dirname $WEBROOT)
rm $SRC/owncloud-*.tar.bz2
chown -R root:root $WEBROOT
chown -R www-data:www-data $WEBROOT/config
chmod 775 $WEBROOT/config
mkdir -p $WEBROOT/data
chown -R www-data:www-data $WEBROOT/data

# configure apache
a2dissite default
a2ensite owncloud
a2enmod rewrite

# start services
/etc/init.d/mysql start

# setup the database
MYSQL_BATCH="mysql --user=root --password=$MYSQL_PASS --batch"
MYSQL_ADMIN="mysqladmin --user=root --password=$MYSQL_PASS"

$MYSQL_ADMIN create $DB_NAME
$MYSQL_BATCH --execute "grant all privileges on $DB_NAME.* to $DB_USER@localhost identified by '$DB_PASS'; flush privileges;"

# stop services
/etc/init.d/mysql stop

