#!/bin/bash -e
# regenerate owncloud salt and mysql password

. /etc/default/inithooks

CONF=/var/www/owncloud/config/config.php

SALT=$(mcookie)
sed -i "s|passwordsalt.*|passwordsalt\' => '$SALT',|" $CONF

PASSWORD=$(mcookie)
sed -i "s|dbpassword.*|dbpassword\' => '$PASSWORD',|" $CONF
$INITHOOKS_PATH/bin/mysqlconf.py --user=owncloud --pass="$PASSWORD"

