#!/bin/bash -e
# regenerate owncloud salt and mysql password

. /etc/default/inithooks

CONF=/usr/share/owncloud/config/config.php

SALT=$(mcookie)
sed -i "s|passwordsalt.*|passwordsalt\' => '$SALT',|" $CONF

INSTANCEID=$(mcookie | cut -b -13)
sed -i "s|instanceid.*|instanceid\' => '$INSTANCEID',|" $CONF

PASSWORD=$(mcookie)
sed -i "s|dbpassword.*|dbpassword\' => '$PASSWORD',|" $CONF
$INITHOOKS_PATH/bin/mysqlconf.py --user=owncloud --pass="$PASSWORD"

SECRET=$(mcookie)$(mcookie)
sed -i "s|secret.*|secret\' => '$SECRET',|" $CONF
