#!/bin/bash -e
# regenerate owncloud mysql password

. /etc/default/inithooks

CONF=/var/www/owncloud/config/config.php
PASSWORD=$(mcookie)

sed -i "s|dbpassword.*|dbpassword\' => '$PASSWORD',|" $CONF
$INITHOOKS_PATH/bin/mysqlconf.py --user=owncloud --pass="$PASSWORD"

