#!/bin/bash -e
# set nextcloud admin password and domain to serve

. /etc/default/inithooks

[ -e $INITHOOKS_CONF ] && . $INITHOOKS_CONF
$INITHOOKS_PATH/bin/nextcloud.py --pass="$APP_PASS" --domain="$APP_DOMAIN"
