#!/bin/bash -e
# set owncloud admin password and domain to serve

. /etc/default/inithooks

[ -e $INITHOOKS_CONF ] && . $INITHOOKS_CONF
$INITHOOKS_PATH/bin/owncloud.py --pass="$APP_PASS" --domain="$APP_DOMAIN"

